steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/station-rate/station-rate-img', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/station-rate/station-rate-img']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'station-rate', '--image', 'gcr.io/station-rate/station-rate-img', '--region', 'asia-northeast1']
images:
- gcr.io/station-rate/station-rate-img